### ISSUE TITLE
Click outside modal should close the modal

### ISSUE THREAD

**Issue by draperunner** [entur/shamash#21]
If you click "Search for ID" in the top menu, a wild modal appears. The only way to close this modal is to press the X in the top right of it. It should also be possible to click anywhere outside the modal to close it.

![image](https://user-images.githubusercontent.com/4339443/66044631-50dfbe00-e522-11e9-9154-4c52ed7c548d.png)

**Comment by Hrily** [comment]
Hey Mats
Can I take this up?

**Comment by draperunner** [comment]
Yes, go ahead @Hrily!

**Comment by BhathiyaTK** [comment]
Hello @draperunner! Can I also take this one?

**Comment by draperunner** [comment]
I think maybe one person per issue is enough. 😄How about this one, @BhathiyaTK: https://github.com/entur/shamash/issues/20?

**Comment by Hrily** [comment]
Cool 👍 

Also, to make it obvious, we should be adding a backdrop to modal. In that way, user knows that the search modal is the only region to interact and the backdrop will act as region to cancel.

**Comment by draperunner** [comment]
That sounds like a good idea, @Hrily. Feel free to have a go at it. Maybe in a separate PR?

**Comment by echeveria** [comment]
Hi, see my pull request if it is OK for you.
