### ISSUE TITLE
Initialize ESLint with recommended rules

### ISSUE THREAD

**Issue by draperunner** [entur/shamash#23]
We should add ESLint in order to ensure basic code quality and consistency. The ESLint config should extend `eslint:recommended` and recommended rules for React.

Other rules
* indent: 4 spaces
* semicolon: never

Let's also add a script in package.json so we can use `npm run lint` for running ESLint.

**Comment by RiyaJohn** [comment]
Can i work on this

**Comment by draperunner** [comment]
Yes! @RiyaJohn

**Comment by dewstend** [comment]
> Yes! @RiyaJohn

You should assign him this issue to avoid multiple people working on this.
