### ISSUE TITLE
Support prefers-color-scheme

### ISSUE THREAD

**Issue by draperunner** [entur/shamash#26]
Today we support light and dark modes which can be toggled with a button in the menu. See pic: 
![image](https://user-images.githubusercontent.com/4339443/66242610-37956800-e702-11e9-8ff3-51bbf21def74.png)

We should also support the cool [prefers-color-scheme CSS media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) which detects the user's theme preference set in the operating system.

Today's theme preference is saved in `localStorage`. The logic for setting happens on page load in App.js:

```
let logo
if (window.localStorage.getItem('theme') === 'dark') {
  require('../css/darktheme.css')
  logo = require('../static/img/entur-white.png')
} else {
  logo = require('../static/img/entur.png')
}
```

The `darktheme.css` stylesheet is loaded if "dark theme" is set in localStorage. The button for switching theme simply updates localStorage.

I'm not sure what's the best way of implementing this is, but if **you** would want to have a go at it, feel free! 🎉

**Comment by Addile** [comment]
I'll work on this if it's okay.

I'm thinking about doing the check:

1. if `theme` was explicitly set (in localstorage already) and use the specified theme.
2. otherwise use dark mode if `prefers-color-scheme: dark` is set.
3. fall back to light theme.
