### ISSUE TITLE
Tweak dark theme colors

### ISSUE THREAD

**Issue by draperunner** [entur/shamash#28]
The dark mode is nice, but some colors have too low contrast.

1) The comma is black and basically invisible
![image](https://user-images.githubusercontent.com/4339443/66243490-239f3580-e705-11e9-9d18-c2c4565a27d2.png)
Do you see the comma between `10` and `omitNonBoarding`? No? It's there. It should be much lighter.

2) The curly brackets, colon and parenthesis are too dark
![image](https://user-images.githubusercontent.com/4339443/66243596-63feb380-e705-11e9-8e04-96244ea98542.png)

3) The text in the top menus is too light
![image](https://user-images.githubusercontent.com/4339443/66243652-9ad4c980-e705-11e9-99d5-b453850a443d.png)

**Comment by tfidfwastaken** [comment]
Hi, I'd like to give this a shot!

**Comment by draperunner** [comment]
@tfidfwastaken go ahead!

**Comment by draperunner** [comment]
Closed by #31
