### ISSUE TITLE
Setup TypeScript for React project, convert one file

### ISSUE THREAD

**Issue by draperunner** [entur/shamash#50]
This is a Node.js and React project. Having TypeScript would be very nice.

A pull request would be greatly appreciated, that
* Sets up a proper TypeScript config (`tsconfig.js`)
* Converts at least one file from .js to .ts (or .tsx) in src/ to prove it works

This project does have a Node.js server, but it has no build (transpilation/compilation) step. Therefore it is sufficient to only consider the React frontend part for now. 

The React app is based on Create React App, and therefore the `react-scripts` package is used for building and running it.

**Comment by sandipndev** [comment]
I can definitely try on that! Also, I love GraphQL.
Please assign me and I will do it 😁

**Comment by draperunner** [comment]
Great, @sandipndev. You're assigned! Thanks for helping out. :)

Please ask if you have any questions.

**Comment by sandipndev** [comment]
Apparently whenever I `yarn start` after conversion to typescript, I get an internal error of the [GraphiQL](https://github.com/graphql/graphiql) package. Any idea as to how to fix?

```
Failed to compile.

/home/sandipndev/HacktoberFest/shamash/node_modules/graphiql/dist/components/HeaderEditor.d.ts
TypeScript error in /home/sandipndev/HacktoberFest/shamash/node_modules/graphiql/dist/components/HeaderEditor.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type * as CM from 'codemirror';
      |             ^
    2 | import React from 'react';
    3 | declare type HeaderEditorProps = {
    4 |     value?: string;
```

**Comment by draperunner** [comment]
Hi! It seems like "Type only imports" came in TypeScript v3.8: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

I see you have installed TypeScript v3.7. Please try installing version ^4.0.3 (the latest) and see if that helps.

**Comment by draperunner** [comment]
How's it going, @sandipndev? :)
